= Vision: {project-name}
Ahmad Alrmih <s86396@htw-dresden.de>; Maurice Harnisch <s87128@htw-dresden.de>; Marius Hoffmann <s86306@htw-dresden.de>; Eric Hübel <s86462@htw-dresden.de>; Victor Saeed <s87082@htw-dresden.de>; Luisa Wehner <s87064@htw-dresden.de>; Gabriel Wulkow Moreira da Silva <s87063@htw-dresden.de>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
Der Zweck dieses Dokuments ist es, die wesentlichen Bedarfe und Funktionalitäten des Systems {project-system-name} überblicksartig zu beschreiben. Der Fokus liegt auf den Fähigkeiten, die von Stakeholdern und adressierten Nutzern benötigt werden, und der Begründung dieser Bedarfe. Die Details, wie das System {project-system-name} diese Bedarfe erfüllt, werden durch User Stories im Product Backlog sowie dem UX-Konzept beschrieben.

=== Zweck
Der Zweck dieses Dokuments ist es, die wesentlichen Anforderungen an das System aus Sicht und mit den Begriffen der künftigen Anwender zu beschreiben.

=== Gültigkeitsbereich (Scope)
Dieses Visions-Dokument bezieht sich auf das System {project-system-name}, das von <Team> entwickelt wird. Das System wird es <Zielkunde/Auftraggeber> erlauben, <Hauptfunktionen> zu nutzen, um damit <Vorteile> zu erreichen / <Aufgabe> zu erleichtern / <Problem> zu lösen.

=== Definitionen, Akronyme und Abkürzungen
//Verweis passend zum Belegabgabe-Template se1_belegabgabe_t00.adoc
Siehe <<#glossary, Glossar>>.
//Siehe <<./glossary.adoc#glossary, Glossar>>.

=== Referenzen
(hier externe Verweise zu anderen Dokumenten, Quellen, Standards etc. einfügen, sofern notwendig)


== Positionierung

=== Fachliche Motivation
In einem zunehmend hektischen Alltag fällt es vielen Menschen schwer, ihre persönlichen Ziele im Blick zu behalten und nachhaltige Verhaltensänderungen umzusetzen. Obwohl die Bedeutung von Routinen für Gesundheit, Produktivität und Wohlbefinden allgemein anerkannt ist, fehlt es oft an geeigneten Werkzeugen zur Unterstützung dieses Prozesses. Klassische To-do-Listen, Kalender oder allgemeine Produktivitätstools sind oft zu unflexibel oder unübersichtlich, wenn es um langfristige Gewohnheitsbildung geht. Hier setzt unser Projekt an: Ziel ist es, eine Habit-Tracking-App zu entwickeln, die Menschen hilft, positive Verhaltensweisen zu etablieren, schädliche Muster abzulegen und bewährte Routinen aufrechtzuerhalten – mit einem klaren Fokus auf Selbstreflexion und individueller Anpassbarkeit. Die angestrebte Verbesserung liegt in einer intuitiven, motivierenden und datengestützten Lösung zur kontinuierlichen Verhaltensentwicklung.

=== Produktvision
//Eine Produktvision beschreibt das Einsatzziel der Anwendung und sorgt für ein gemeinsames Ziel und Verständnis für alle Beteiligten im Projekt. Geben Sie in knapper Form übersichtsartig die Positionierung der angestrebten Lösung im Vergleich zu verfügbaren Alternativen dar. Das folgende Format kann dazu verwendet werden:


[cols="1,3"]
|===
| Für | [Menschen, die ihre Gewohnheiten bewusst gestalten wollen]
| die | [gezielt Verhaltensweisen etablieren, verändern oder beibehalten möchten]
| ist das  | [Produkt]
| eine  | [digitale Habit-Tracking-App]
|die |[die bewusste Selbststeuerung durch flexibles Tracking und Selbstreflexion unterstützt]
| anders als | [klassische Kalender- oder To-do-Apps]
| kann unser Produkt | [gezielt beim Angewöhnen, Abgewöhnen und Stabilisieren von Verhaltensweisen helfen und persönliche Muster sichtbar machend]
|===


//Beispiel
//[cols="1,3"]
//|===
//| Für | Studierende der HTWD
//| die | zu wenig Zeit in der Mittagspause zum Essen haben
//| ist   | Flying Burger
//| ein  | Lieferdient für Burger
//| der  | per Drohne liefert
//| anders als | landgestützte Lieferdienste
//| kann unser Produkt |  durchs Fenster direkt in den Hörsaal liefern.
//|===

== Stakeholder Beschreibungen

=== Zusammenfassung der Stakeholder

[%header, cols="1,3,3"]
|===
| Name | Beschreibung | Verantwortlichkeiten

//| [Benennung des Stakeholders (als Rolle)]
//| [Kurze Beschreibung des Stakeholders und seiner Ziele]
//| [Fassen Sie die wesentlichen Verantwortlichkeiten des Stakeholder mit Bezug auf das zu entwickelnde System kurz zusammen, d.h. ihr besonderen Interessen. Beispiele: Dieser Stakeholder sorgt dafür, dass das System gewartet wird / dass die angezeigten Daten aktuell sind / überwacht den Projektfortschritt / usw.]

|Standards und Gesetze
|Umfasst rechtliche, normative und regulatorische Instanzen
a| * Rechtskonformität (z.B. Einhaltung der DSGVO, Urheberrecht, IT-Sicherheitsgesetz)
  * Sicher (z.B. nach ISO/IEC 27001 für Informationssicherheit) 
  * Transparenz und Nachvollziehbarkeit (z.B. Dokumentationspflichten)
  * Interoperabilität unterstützend (z.B. durch Einhaltung offener Standards wie HL7 im Gesundheitswesen)
  * Barrierefreiheit gewährleistend (z.B. gemäß Barrierefreiheitsstärkungsgesetz (BFSG) oder WCAG)
  * Nachhaltig  (z.B. durch Umweltauflagen oder Energieeffizienzstandards)
|Entwicklungsteam
|Allgemeine Entwickler, UI-Designer, Tester
a| * verständlichen, gut lesbaren, kommentierten Code schreiben
   * möglicherweise an Style Guides halten
   * Git-Commits mit kurzer, aber klarer Nachricht und optionaler Beschreibung
   * Einhaltung von Deadlines

|Nutzer
|Personen die, die App letztendlich Nutzen werden
a|* Feedback zur Usability geben
  * Regelmäßige Nutzung der App im Alltag
  * Formulierung von Wünschen, Bedürfnissen und Anforderungen für die Weiterentwicklung
|Produktgegner
|Personen, die vom Produkt noch nicht überzeugt sind
a| * Kritikpunkte äußern, die als Grundlage für Verbesserungen dienen können
   * Ziel von Marketing- und Überzeugungsmaßnahmen

|===

Die Verfeinerung der Stakeholder, die das System benutzen, wird im UX-Konzept mittels Personas vorgenommen.


== Produktüberblick

=== Bedarfe und Hauptfunktionen
//Vermeiden Sie Angaben zum Entwurf. Nennen wesentliche Features (Produktmerkmale) auf allgemeiner Ebene. Fokussieren Sie sich auf die benötigten Fähigkeiten des Systems und warum (nicht wie!) diese realisiert werden sollen. Geben Sie die von den Stakeholdern vorgegebenen Prioritäten an.


[%header, cols="4,1,4,1"]
|===
| Bedarf | Priorität | Features / Funktionen | Geplantes Release
| Nutzer wollen tägliche Gewohnheiten verfolgen. | Hoch | Tägliches Abhaken von Gewohnheiten | Version 1.0
| Nutzer möchten an ihre Gewohnheiten erinnert werden. | Mittel | Push-Benachrichtigungen/Reminder | Version 1.1
| Nutzer wollen sehen, wie konsequent sie sind. | Hoch | Statistiken & Streak-Tracking | Version 1.2
| Nutzer möchten ihre eigenen Gewohnheiten anlegen. | Hoch | Eigene Habits erstellen & bearbeiten | Version 1.0
| Nutzer wollen motiviert bleiben. | Niedrig | Belohnungssystem / Level-Ups | Version 1.3
| Nutzer wollen mehrere Gewohnheiten gleichzeitig verwalten. | Hoch | Übersicht über mehrere parallele Habits | Version 1.0
| Nutzer möchten Gewohnheiten kategorisieren. | Mittel | Kategorien oder Tags für Habits | Version 1.2
| Nutzer möchten ihre Fortschritte visualisiert sehen. | Mittel | Diagramme und Fortschrittsbalken | Version 1.2
| Nutzer wollen flexibel mit Zeiträumen umgehen. | Mittel | Wöchentliche und monatliche Ziele | Version 1.3
| Nutzer möchten die App individuell anpassen können. | Niedrig | Theme-Auswahl (Hell/Dunkel etc.) | Version 1.4
| Nutzer wollen durch Challenges motiviert werden. | Niedrig | Habit-Challenges (z.B. 21-Tage-Challenge) | Version 1.5
|=== 

=== Zusätzliche Produktanforderungen
//Zutreffendes angeben, nicht zutreffendes streichen oder auskommentieren
Hinweise:

. Führen Sie die wesentlichen anzuwendenden Standards, Hardware oder andere Plattformanforderungen, Leistungsanforderungen und Umgebungsanforderungen auf
. Definieren Sie grob die Qualitätsanforderungen für Leistung, Robustheit, Ausfalltoleranz, Benutzbarkeit und ähnliche Merkmale, die Qualitätsanforderungen an das geplante Produkt beschreiben.
. Notieren Sie alle Entwurfseinschränkungen, externe Einschränkungen, Annahmen oder andere Abhängigkeiten, die wenn Sie geändert werden, das Visions-Dokument beeinflussen. Ein Beispiel wäre die Annahme, dass ein bestimmtes Betriebssystem für die vom System erforderliche Hardware verfügbar ist. Ist das Betriebssystem nicht verfügbar, muss das Visions-Dokument angepasst werden.
. Definieren Sie alle Dokumentationsanforderugen, inkl. Benutzerhandbücher, Onlinehilfe, Installations-, Kennzeichnungs- und Auslieferungsanforderungen.
. Definieren Sie die Priorität für diese zusätzlichen Produktanforderungen. Ergänzen Sie, falls sinnvoll, Angaben zu Stabilität, Nutzen, Aufwand und Risiko für diese Anforderungen.

[%header, cols="4,1,1"]
|===
| Anforderung | Priorität | Geplantes Release
| xx | xx | xx
|===




//falls im vision notwenig:

== Domänenmodell
[plantuml, "{diagramsdir}/syntax-example2",svg]
....
include::{plantumlsdir}/domaenenmodell.puml[]
.... 
 